### ISSUE TITLE
Google Chrome deprecation warnings.

### ISSUE THREAD

**Issue by tammesalu** [goldfire/howler.js#856]
Google Chrome is giving me following warnings when I use Howler in my project:

`howler.js:2213 [Deprecation] GainNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.`

`[Deprecation] AudioParam value setter will become equivalent to AudioParam.setValueAtTime() in M65, around March 2018  See https://webaudio.github.io/web-audio-api/#dom-audioparam-value for more details.`

Does anyone know what are those warnings and can they be addressed in Howlers code?

**Comment by klaasman** [comment]
It is only a couple of weeks left until January, so is it possible to have this fix released to NPM?

**Comment by goldfire** [comment]
This just got pushed to npm in 2.0.6.

**Comment by klaasman** [comment]
Great, thanks!

**Comment by Stenerson** [comment]
I'm still getting the following deprecation warning in `2.0.7`

`[Deprecation] AudioParam value setter will become equivalent to AudioParam.setValueAtTime() in M65, around March 2018  See https://webaudio.github.io/web-audio-api/#dom-audioparam-value for more details.`

It appears that 0b538a7 only addressed the issue with `GainNode.gain.value` but the issues with `rate` still exist.

The culprit is here:
[`sound._node.bufferSource.playbackRate.value = sound._rate;`](https://github.com/goldfire/howler.js/blob/master/src/howler.core.js#L1925)

This should probably also be updated:
[` sound._node.bufferSource.playbackRate.value = rate;`](https://github.com/goldfire/howler.js/blob/master/src/howler.core.js#L1362)

**Comment by goldfire** [comment]
@Stenerson Thanks! Just fixed this with dc0a2cf8d2c0ca17246573de90c7f95f6991438d and will try to get a 2.0.8 release out soon.

**Comment by julesongithub** [comment]
Is the first warning a breaking change?

"GainNode.gain.value setter smoothing is deprecated and will be removed in M64"

I've just updated to M64 and, though I still get the warning, the audio still works.

**Comment by DFortun81** [comment]
[Deprecation] AudioParam value setter will become equivalent to AudioParam.setValueAtTime() in M65, around March 2018   See https://webaudio.github.io/web-audio-api/#dom-audioparam-value for more details.

The error is in reference to **sound._node.bufferSource.playbackRate.value = sound._rate;** within the _refreshBuffer function.

**Comment by goldfire** [comment]
@DFortun81 That was fixed in v2.0.8.

**Comment by DFortun81** [comment]
Yeah, sorry. I didn't see the update.
